[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/terafox.toml"
]

[window]
dynamic_padding = true
opacity = 1.0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
thickness = 0.25
style = { blinking = "On", shape = "Beam" }

[font.normal]
family = "Iosevka"

[font]
size = 12

[scrolling]
history = 50000
multiplier = 4

[window.padding]
x = 4
y = 4

# Break line with Shift+Enter
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
