[general]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#ffaa22"
text = "CellBackground"

[colors.primary]
background = "#111111"
foreground = "#ddd3d7"

[colors.vi_mode_cursor]
cursor = "#ff2020"
text = "CellBackground"

[cursor]
blink_interval = 500
thickness = 0.2
style = { blinking = "On", shape = "Beam" }

[font.normal]
family = "Iosevka"

[font]
size = 17

[scrolling]
history = 50000
multiplier = 4

[window]
dynamic_padding = true

[window.padding]
x = 4
y = 4
