live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#ffaa22"
text = "CellBackground"

[colors.primary]
background = "#111111"
foreground = "#ddd3d7"

[colors.vi_mode_cursor]
cursor = "#ff2020"
text = "CellBackground"

[cursor]
blink_interval = 500
thickness = 0.2
style = { blinking = "On", shape = "Beam" }

[font]
size = 16.7

[font.bold]
family = "Victor Mono"
style = "Bold"

[font.bold_italic]
family = "Victor Mono"
style = "Bold Oblique"

[font.italic]
family = "Victor Mono"
style = "Italic"

[font.normal]
family = "Victor Mono"
style = "Bold"

[scrolling]
history = 40000
multiplier = 4

[window]
dynamic_padding = true

[window.padding]
x = 3
y = 3
