;                __     __
;     ___  ___  / /_ __/ /  ___ _____
;    / _ \/ _ \/ / // / _ \/ _ `/ __/
;   / .__/\___/_/\_, /_.__/\_,_/_/
;  /_/          /___/
;
;
; https://github.com/marcospb19/dotfiles

; Laptop Screen
[bar/eDP]
inherit = bar/main
monitor = eDP
# monitor-fallback =

; HDMI Monitor
[bar/HDMI]
inherit = bar/main
monitor = HDMI-1
monitor-fallback = HDMI-A-0

; Display Port Monitor
[bar/DisplayPort]
inherit = bar/main
monitor = DisplayPort-2

; The bar itself
[bar/main]
enable-ipc = true
modules-left = i3mode pomodoro nest
modules-center = i3
modules-right = kb-layout cpu memory date current-volume

; bottom = true
fixed-center = true
tray-position = right
tray-padding = 2
height = 20
line-size = 1

background = #890f1c1e
foreground = #cbd9d8

border-bottom-size = 1
border-bottom-color = #2a4042

; # # Main font
font-0 = Iosevka:style=bold:pixelsize=9.0;3
; font-0 = Victor Mono:style=bold:pixelsize=12.0;1
; font-0 = terminus:style=bold=50;1
; font-1 = Iosevka Nerd Font:style=regular:antialias=true
padding-left = 2
padding-right = 2
module-margin-left = 1
module-margin-right = 2

; i3wm
[module/i3]
type = internal/i3
format = <label-state>
pin-workspaces = true

; Workspaces
label-focused-foreground = #e6eaea
label-focused-background = #254147
label-focused-underline = #8eb2af

label-unfocused-foreground = #aaa
label-unfocused-underline = #1f3032


label-urgent-foreground = #eee
label-urgent-underline = #fff
label-urgent-background = #aaa

label-visible-foreground = #000
label-visible-background = #bbb
label-visible-underline = #999

; This should work as a one-liner, in my opinion
; label   = "  %index%  "
label-focused   = "  %index%  "
label-unfocused = "  %index%  "
label-urgent    = "  %index%  "
label-visible   = "  %index%  "
; label-focused-padding   = 2
; label-unfocused-padding = 2
; label-urgent-padding    = 2
; label-visible-padding   = 2

; Show i3mode menu on different place
[module/i3mode]
type = internal/i3
fomart = %mode%

label-focused   =
label-unfocused =
label-visible   =
label-urgent    =

label-mode = %mode%
label-mode-background = #254147
label-mode-underline = #7aa4a1
label-mode-foreground = #7aa4a1

; CPU percentage
[module/cpu]
type = internal/cpu
interval = 1.7
label-underline = #7aa4a1

; RAM percentage
[module/memory]
type = internal/memory
interval = 2.3
label-underline = #ffb780

; Current date
[module/date]
type = internal/date
interval = 1
label = " %date% %time% "
label-underline = #cb7985
date = %x
time = %I:%M %p
date-alt = %A, %d %B, %Y,
time-alt = %I:%M:%S %p

; Custom script that shows battery percentage if low
[module/batteryscript]
type = custom/script
interval = 50
exec = dash ~/.config/polybar/batteryscript.sh
label-underline = #6bf

; Custom script that shows volume percentage
[module/current-volume]
type = custom/script
tail = true
exec = climsg listen polybar/update_volume
label-underline = #ad5c7c

; Pomodoro integration with bar
[module/pomodoro]
type = custom/script
tail = true
exec = climsg listen tomate-pomodoro
label-background = #504540
label-underline = #866
label-foreground = #ffb0b0

; setxkbmap integration with bar
[module/kb-layout]
type = custom/script
tail = true
exec = climsg listen kb-layout
label-foreground = #ccc
label-background = #444
label-underline = #999

; Integration with `nest` tool
[module/nest]
type = custom/script
tail = true
exec = climsg listen nest-current-task

label-background = #504540
label-underline = #866
label-foreground = #ffb0b0

; vim: ft=dosini cms=;%s
